### ISSUE TITLE
无法把钦定的图片发送至QQ

### ISSUE THREAD

**Issue by PeronGH** [naco-siren/mogicians-manual#1]
Naïve的QQ说图片不存在，完全是一派胡言！希望作者能修复一下。

还有，我的QQ是修改版的。

**Comment by naco-siren** [comment]
QQ尚未支持新的ContentProvider的分享机制，但考虑到微信已经支持，可能不久之后也能支持吧

**Comment by PeronGH** [comment]
歌曲播放有bug,经常出现点击另一首蛤曲，上一首蛤曲的图标没变，最终使得多首蛤曲左边都显示正在播放却只有最后一首蛤曲在播放。

系统: Android 7.1.2
定制ROM名称：RR
型号: Huawei P9 (EVA-L19)
自定义DPI:380

**Comment by hanxiaochen1019** [comment]
第一次分享的时候点了qq 然后说图片不存在
之后每次点图片就直接跳出qq了没法分享到其它 是我自己的问题吗

**Comment by naco-siren** [comment]
@hanxiaochen1019 请看我之前的回复
