### ISSUE TITLE
建议加入 + 适应夜间模式（黑暗模式）

### ISSUE THREAD

**Issue by WhiteSheep001** [naco-siren/mogicians-manual#100]
如题，晚上明晃晃的不方便学习一个……
![Screenshot_20200207-005323_Settings](https://user-images.githubusercontent.com/30397066/73959498-5de34280-4944-11ea-9e80-d663cd306983.jpg)

**Comment by ludles** [comment]
滋磁

**Comment by StayCuisha** [comment]
滋瓷！

**Comment by meixu0** [comment]
滋瓷！

**Comment by naco-siren** [comment]
这个可以有

**Comment by naco-siren** [comment]
![image](https://user-images.githubusercontent.com/8222638/117604860-48dafd80-b10b-11eb-90e5-d16507d7e1d9.png)

给你加急了，头上三尺有神明
