### ISSUE TITLE
许可证

### ISSUE THREAD

**Issue by linsui** [naco-siren/mogicians-manual#110]
请问是否可以在开源许可证下发布？

**Comment by naco-siren** [comment]
具体点，你要发布什么

谁指使你发布的🤫

**Comment by naco-siren** [comment]
我自己都没想好用那个许可🤭

**Comment by linsui** [comment]
GPL 就很 exciting 了！MIT 也不会 naive。

**Comment by naco-siren** [comment]
那就GPL呗

**Comment by linsui** [comment]
另外请问是否可以在 F-Droid 发布你的应用？

**Comment by naco-siren** [comment]
你可以搬运google play上的apk过去，但只能以你个人名义

**Comment by linsui** [comment]
F-Droid 从源码构建应用，所以我没有办法搬运 apk，感谢你的回复。 😄
