### ISSUE TITLE
我想利用这个app的框架做一个辐射4的app攻略

### ISSUE THREAD

**Issue by Sundance0604** [naco-siren/mogicians-manual#120]
请问这是用android studio搞的吗

**Comment by naco-siren** [comment]
这是个 Flutter project。Flutter的默认IDE是Android Studio。

只要你不怕我这学生时代写着玩的破架构到时候拖你的后腿……

**Comment by Sundance0604** [comment]
太牛了！高中时和同学使用您的软件，得到很多乐趣，想不到这竟是天才的小小创造！

**Comment by Sundance0604** [comment]
请问这个的layout在哪里呀？我想改按键内容……我不是很明白，还请您指点一二
