### ISSUE TITLE
1926，特斯拉，通古斯

### ISSUE THREAD

**Issue by batkiz** [naco-siren/mogicians-manual#13]
大致看了下应用，发现没有这个段子，希望能够添加上。

> 1926年，美国工程师尼古拉斯·特斯拉进行了人类历史上第一次时间旅行实验，成功将一克铁元素送到18年前的1908年，但特斯拉在计算相对空间关系时，仅计算了地球，太阳以及银河系的运动轨迹，而忽略了宇宙膨胀因素（特斯拉不相信这个理论）使得这一克铁元素没有出现在预计的美国中部，而是出现在了数千英里外的西伯利亚。
这次穿越实验的后果是灾难性的，1908年的宇宙物质总量被凭空增加了整整一克，打破了空间连续性的平衡，一克铁元素转化为能量和空间的物理过程在一普朗克单位时间中完成，引发了剧烈爆炸，即通古斯大爆炸。
而1926年的宇宙，物质总量被凭空减少了整整一克，在穿越时间点造成时空扭曲，时空震波散射了数千英里，在中国扬州地区产生自干涉，使得一名男婴出现基因突变，获得了以秒为单位的时空干扰能力。  

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi Redmi Note 4X 发送_

**Comment by naco-siren** [comment]
@batkiz 已添加，感谢资瓷
