### ISSUE TITLE
你搞得这个事情啊，excited

### ISSUE THREAD

**Issue by billchenchina** [naco-siren/mogicians-manual#14]
不资磁 Huawei MT7啊

**Comment by billchenchina** [comment]
![77e725dfcc6051e2](https://user-images.githubusercontent.com/7758042/28757759-910c0c76-754f-11e7-96fb-d8b97cbed03e.jpg)

**Comment by naco-siren** [comment]
@billchenchina  https://github.com/naco-siren/mogicians_manual_public_release/releases

**Comment by billchenchina** [comment]
@naco-siren 试过了，下载后并不能安装
```解析包时出现问题。```
试了1.0.1~1.1.2最新的 release 版都不行。。。
```Android 4.4.2```
可能是安卓版本的坑？

**Comment by naco-siren** [comment]
@billchenchina Android 5.0起步

**Comment by BROBIRD** [comment]
mate7不是早就Android6.0了吗

**Comment by naco-siren** [comment]
@billchenchina 我不知道Mate7不兼容的具体原因，毕竟是华为的产品，有各种奇怪的问题也见怪不怪了。
