### ISSUE TITLE
关于表情发送的问题

### ISSUE THREAD

**Issue by colasama** [naco-siren/mogicians-manual#18]
长按【逗】内表情江会跳到发送邮件页面，如何破？
![default](https://user-images.githubusercontent.com/6457253/28876909-4e1193fc-77cd-11e7-916f-0ed93c59d3be.png)

**Comment by naco-siren** [comment]
说明你第一次长按的时候打开方式用的邮件并且选择了“总是”。
你需要到设置->应用里，把邮件的默认打开方式重置。

**Comment by colasama** [comment]
不过在第一次长按的时候就直接弹出了邮件页面，同时在另外两台不同型号的机器上也出现了同样的情况。而且可能是国内深度定制的原因，设置内并没有更改默认打开方式的选项，系统7.1.1，供您参考下。

**Comment by naco-siren** [comment]
@colasama 方便告诉我这几台机子都是什么品牌什么型号什么rom么

**Comment by colasama** [comment]
努比亚Z17/Nubia UI/7.1.1
小米6/MIUI/7.1.1
红米Note4/MIUI/6.0

**Comment by colasama** [comment]
抱歉，重新问了一下，只有Z17出现了这个问题。其余两个都是因为机主自身姿势水平不足所致。
