### ISSUE TITLE
还是要学习一个

### ISSUE THREAD

**Issue by kungchun** [naco-siren/mogicians-manual#19]
作为一个hath，我们切记要不断提高自己的知识水平，但是首先应该是要有一个实事求是的态度。今天，作为一个长者，我今天要小小的得罪你一下，你这个“【2000年接受美国CBS记者麦克·华莱士的节目访谈】”中的文本根本不是我蛤所说，而是一个名叫“愚夫”的人所写，而这个愚夫根本看不起我蛤同Wallace的谈话，甚至嘲笑我蛤是“最没有知识最没有品味最没有格调的领导人”，你们居然还拿他的“拟江泽民答华莱士”作为学习资料，作为一个老hath i'm so angry!

**Comment by naco-siren** [comment]
@massacre89 老hath您好，请问哪里有贵蛤的原版对白？

**Comment by kungchun** [comment]
http://yyyyiiii.blogspot.jp/2010/03/cbs-200060.html?m=1
这是我钦点的翻译
@naco-siren

**Comment by kungchun** [comment]
http://www.cbsnews.com/news/jiang-zemin-talks-with-wallace/
这是钦点的原文

**Comment by naco-siren** [comment]
@massacre89 已fix，谢谢老hath滋磁。
