### ISSUE TITLE
多首蛤曲左边显示正在播放

### ISSUE THREAD

**Issue by PeronGH** [naco-siren/mogicians-manual#2]
歌曲播放有bug,经常出现点击另一首蛤曲，上一首蛤曲的图标没变，最终使得多首蛤曲左边都显示正在播放却只有最后一首蛤曲在播放。

系统: Android 7.1.2
定制ROM名称：RR
型号: Huawei P9 (EVA-L19)
自定义DPI:380

希望作者修复，谢谢。
还有，Google Play上的版本比Github上编译的版本新。希望更新一下Github上的版本。

**Comment by PeronGH** [comment]
复现方法找到了！
只要播放蛤曲时去其他界面，回来时点另一首曲子就会出现此Bug

**Comment by naco-siren** [comment]
谢谢！我争取尽早fix

**Comment by naco-siren** [comment]
@YangZichen 已fix，请等待商店推送更新。
