### ISSUE TITLE
一首词，原作者不详

### ISSUE THREAD

**Issue by lonzoen** [naco-siren/mogicians-manual#20]
山不在高，另请高明。水不在深，亦可赛艇。虽是支持，没有钦定。要按基本法，记者太年轻。谈笑华莱士，往来宋煮樱。不可见得风，是得雨。无港媒之快速，有知识之水平。要弄大新闻，这样子不行。长者云：无可奉告。

**Comment by naco-siren** [comment]
@tengxunkuku 这首是陋室铭，本身就已经收录了。

**Comment by lonzoen** [comment]
在知乎上看的
古今中外有哪些人真正算得上「挽狂澜于既倒，扶大厦之将倾」？

是谁禁止了军队从商？
是谁平治了洪水汤汤？
是谁稳定了通货膨胀？
是谁坚持了改革开放？
是谁任命了铁血宰相？
是谁捣毁了邪教道场？
是谁收回了澳门香港？
是谁挡住了金融风暴？
是谁加入了世界商贸？
是谁提出了科教兴邦？

他改变了中国！
倒数第三句有点不押韵，希望能改改。
