### ISSUE TITLE
增加一个段子

### ISSUE THREAD

**Issue by ZBTJ** [naco-siren/mogicians-manual#24]
来自微博：

老虎失足从山崖摔下，幸亏落在树上，大难不死。狐狸拍马屁说：“大王，您刚才落下时喊的那一声都特别威风”。老虎得意地说：“因为我是坠吼的”。 ​

**Comment by ZBTJ** [comment]
童童带回了一瓶压缩气体，打开之后，
整个教室突然银亮亮的。
童童懵了：“不对，我制取的是有机物啊？”
经过反思检查，发现可能是水浴锅没洗干净导致产物变质。
他恍然大悟，在笔记本上写下了：
疑似剩夹锅里垢，制取芘氟获银气

**Comment by naco-siren** [comment]
@ZBTJ 感谢投稿，已收录！
