### ISSUE TITLE
最新版指南“唱”安卓7.0无法设定铃声

### ISSUE THREAD

**Issue by ghost** [naco-siren/mogicians-manual#25]
即使授予改变系统设置权限也无法设置。希望增加导出到本地的功能
还有就是有的歌不知道原曲，希望有看原曲名的功能

**Comment by naco-siren** [comment]
@zxzh0438 请问你的机型、系统版本是什么。

**Comment by ghost** [comment]
三星note5国行，安卓7.0，n9200zcu3dqe3。

**Comment by naco-siren** [comment]
@zxzh0438 不懂……不过我会试着搞一下

**Comment by naco-siren** [comment]
这个功能bug太多，我移除了
但是姿势水平较高的同志可以自己写一下，开个PR
