### ISSUE TITLE
名字错了

### ISSUE THREAD

**Issue by ghost** [naco-siren/mogicians-manual#3]
在 考据-唱什么歌中，尤克里里应为夏威夷吉他更好，而歌曲名应为 Ahona Oe(或 Ahona 'oe)

**Comment by ghost** [comment]
抱歉打错了
在 考据-奏什么乐中，尤克里里应为夏威夷吉他更好，而歌曲名应为 Ahona Oe(或 Ahona 'oe)

**Comment by naco-siren** [comment]
@Flyfish233 Fixed. 谢谢这位同志
