### ISSUE TITLE
几点小建议

### ISSUE THREAD

**Issue by FatgooseX** [naco-siren/mogicians-manual#31]
1.在那个关于 Jack 和 Gray 的段子中，“缺告诉她……”应为“却告诉她……”。
2.魅蓝 metal [Flyme 6,YunOS 3.16(基于Android 5.1)]，长按蛤曲标题，但无法设置为铃声。
3.建议在搜索结果中高亮关键字，以便让广大蛤丝迅速找到要搜索的内容。那是坠吼的!
4.毕竟这是一个指南，在应用大小允许的情况下，可以适当加入一些膜蛤入门资料，比如说苟、+1s、鸭嘴笔等梗的起源，以及蛤三篇的录音或视频等，让新手膜法师们迅速提高姿势水平。
写得有点多，还望作者多多理解。

不用这个 app 遗憾了，这么好的应用，作者要宣传宣传，hath 们也要宣传宣传。
我作为一名 hath，也为你们宣传宣传，以后这里就人山人海了。

**Comment by naco-siren** [comment]
1. 已Fix
2. 3. 开源版本还没做
4. PR大欢迎
