### ISSUE TITLE
微小的建议

### ISSUE THREAD

**Issue by ghost** [naco-siren/mogicians-manual#33]
1.交互:触摸蛤曲框架即可播放
2.内容:建议开放上传功能，审核后发布
3.功能:建议新增一个消息推送模块，以便在特殊的日子推送消息
4.其他:作者最好不要在APP内留下大陆网站的账号信息，源代码也是如此

祝作者闷声大发财

**Comment by ghost** [comment]
另外，分享一个怒斥记者清晰而完整的版本
https://youtu.be/QamNk17hiLo

**Comment by naco-siren** [comment]
@ZHCSOFT 
1. 设计成只有按到按钮才播放暂停，是为了避免手粗/误触。
2、3. 没钱搞服务器，入不敷出。
4. 已去除，谢谢关心。
