### ISSUE TITLE
我也不知道我一个文科生怎么就来github提建议了

### ISSUE THREAD

**Issue by AllRussian** [naco-siren/mogicians-manual#34]
1.希望开放一个投稿的通道，毕竟长者流传在民间的表情包还是很多的
2.希望增加蛤三篇视频
3.制作者不要总搞个大新闻，惊动中央把你调到北京就不吼了
4.这个应用目前还是tooyoung，应该推广一番，知乎这个膜法师聚集地就很吼！

**Comment by naco-siren** [comment]
@AllRussian 
1. 现在开源了，投稿请随意
2. 同上
