### ISSUE TITLE
投稿一个失传的知乎段子

### ISSUE THREAD

**Issue by Narugakuruga** [naco-siren/mogicians-manual#35]
已经被删了，好像是匿名用户写的
原文：

我听一老爷爷讲过这么个故事：

青蛙原本生活的栖息地在河流中，那时候的青蛙，还没有长寿啊，不死啊之类的象征，也不会被人们膜拜，当做永生不死的图腾。在他们的族群中，最有威望的是长老。

蛙在下沙村旁的河里，那里是他的天下，过得也是自由自在。直到有一天，他听说下沙村北面的南洼村出事了，据说小蝌蚪们团成了一团要堵塞河道。敏锐的直觉告诉他事情不太对头，果然没多久就接到了长老的一纸诏书，让他去南洼村。长老告诉他，想让他来当接班蛙，蛙诚惶诚恐，当时就给长老呱了两声。这算是应下来了，小蝌蚪们的事儿也告一段落，蛙从下沙村河段搬到了南洼村河段，也走上了一段不可思议的道路。

南洼村河段虽然比下沙村河段水冷，但是蛙还算适应。这天沿着河岸溜达，突然看到岸边上放了一个绿色的筐，这一瞅，他的眼神却挪不开了，那一眼究竟是一秒还是一生，他也说不清。可他毕竟是长老，定了定神，只好继续溜达着。现在的他，虽说身体走过了河岸，心却走不过那筐。

自从上次的相遇，他时不时会偷偷去筐边溜达，听刮风时筐的响声，仿佛在弹拨灵魂。他暗自下定决心，一定要让所有的蛙都听到！可是他始终只能偷偷去听，偷偷去看，偷偷去陪。恋爱中的蛙的卑微都差不多。

一晃就是十三年，筐还是那个筐，他已经老了。这十三年间他也没有放弃跟生老病死做斗争，他发现，当他获得别蛙的第一能级组电子时，他的寿命会有所增长，虽然是线性增长，但蛙的数量是庞大的。他看着筐，回想着这十三年来的风风雨雨，视线开始模糊，他不要再顾忌这世俗的枷锁，不要再躲避，不要再承受！他爬上了岸，驮起筐，临走前看了眼河里，轻声说了句：田野有希望，让她去陪你。

据说没有人再见到那蛙，也没有人再见到筐。

老爷爷讲完了故事，我瞅了眼远处的天空，乌云密布。我说，快下雨了，您要不快进去吧。老爷爷笑了笑，傻孩子，雨下不来。

**Comment by naco-siren** [comment]
@realJiangZemin 谢谢投稿，不过我感觉这个段子不是很搞笑啊……？

**Comment by Narugakuruga** [comment]
但是很感人是
