### ISSUE TITLE
投稿一个段子

### ISSUE THREAD

**Issue by Narugakuruga** [naco-siren/mogicians-manual#36]
我还是很喜欢你，莱士是你，宝华是你。我还是很喜欢你，硬点是你，滋辞是你。我还是很喜欢你，图样是你，森破是你。我还是很喜欢你，怒斥是你，谈笑是你。我还是很喜欢你，天下是你，兴亡是你。我还是很喜欢你，下雨是你，晴朗是你。我还是很喜欢你，奋斗是你，进程是你。我还是很喜欢你，惭愧是你，微小是你。我还是很喜欢你，扬州是你，上海是你。我还是很喜欢你，吉他是你，二胡是你。我还是很喜欢你，英语是你，俄语是你。我还是很喜欢你，京剧是你，书法是你。我还是很喜欢你，像黑框的眼镜，不离不弃。我还是很喜欢你，像齐胸的裤腰，生死相依。我还是很喜欢你，像江都的细雨，落满大地。我还是很喜欢你，像运河中的明灯，中元升起。

**Comment by Narugakuruga** [comment]
还有这个离骚体怒斥


       上四载而四月兮，燕粤藩乎帝京。既欢娱以交接兮，若有声焉堂下。
     “董卿复而以镇藩兮，岂君心之所悦？”皆震悚而怵惕兮，唯三缄以无言。计专专而莫对兮，君回首以宣诉。“何娉节而敏睿兮，朕钦之以连复。” 
     “欧罗巴之有斯兮，君操之以悖路。舞权柄而阴功兮，缪粤藩之法度。窃惶惶而迷惑兮，君何言以为对？恐君怒余诳谣兮，唯彭臣之余说。” 
     “子报者其铭之兮，子职乎间以舍趣。风飒飒而泬寥兮，猋浮云其上蔽。东君昭昭而复见兮，岂皇天之霪溢？子复诵此谣诞兮，子昝责其庶几。” 
      "何秋霖而春卜兮，夸言彼乎此间？私自疑而烦榐兮，岂吾君之硬点？”
     “朕何意以硬点兮？皆粤藩之本纲。子狂悖以责怨兮，何瞀乱之无当？彼恶语而诛心兮，朕诚然无以告。羌愤懑而恚怼兮，朕何为以相告？朕无意以硬点兮，徒敬对之乃辞。皇天不雨而甑坏兮，何不引水而滋瓷？既滋瓷以此道兮，朕堂堂告以斯。何报者之鄙薄兮？羌怙恶以无行。
     “子智识之疏浅兮，徒佯仿乎泰西。朕观子之陋德兮，其复进而学习！何孺子之青春兮？何朕躬之德高。身百战而广见兮，彼泰西吾以逍遥。美利坚而有贤兮，瓦勒斯之尧尧。朕圣德而久历兮，曾彼朕之谈笑。报者其习姿势兮，识得唔识得咁？既姿势之阙亏兮，朕焦之以中肝。何子辈之昭彰兮？唯驰骋之疾步。然有问之新泊兮，桑滩兮携衣服。朕伤之以切切兮，识得唔识得啊！非报者之子侪兮，朕长者以言之：纷吾既有此博见兮，必告子以经验。
      “汉家有此箴谚兮，闷声而发大财。何朕心之嘉悦兮？唯寂漠而缄缄。奈何子之热情兮，朕愠愠而有言。觇宣传之偏差兮，朕恐其将子昝！何硬点夫董卿兮？朕诚哉无此意。彼既任乎粤藩兮，岂熟视而不滋瓷？”
     “余诚明乎斯道兮，岂及其乎连复？”
     “连复兮亦如是，皆禀遵兮本纲。朕懿兮其将至，粤藩兮亦皇疆！何子侪之俇攘兮？谣诼朕以钦定！幸批判之逆为，盍携衣而返境！子荒唐以废度，朕遵谨以安规！事亹亹而中疾兮，蹇淹留而无知。春秋逴逴而日下兮，朕恐子之就木。亏此日之嘉燕兮，微诸子之有触。赖皇天之厚德兮，还将子之无怒。”

**Comment by naco-siren** [comment]
@realJiangZemin 已收录，谢谢！
