### ISSUE TITLE
童话镇（膜法堡）

### ISSUE THREAD

**Issue by ghost** [naco-siren/mogicians-manual#4]
传说有个膜法堡
有个长者不得了
每个记者得她指导
都盼望世界更美好
时间众筹真的奇妙
一个滑稽加上一秒
一不小心就会一团糟
我有个 好提议
就约定在一起
去寻找膜🐸法的秘密
一看到华莱士
特别是西方的
我知道我无能为力
巴啦啦小膜仙 红衣一穿上
就展开xu命的一战
巴啦啦小膜仙
红衣一穿上
会实现最吼的梦想 有了时间力量
我的膜力变强
战胜灰暗忧伤
我们才能够成长

**Comment by naco-siren** [comment]
@sdtalyk 已添加。谢谢同志
