### ISSUE TITLE
关于铃声设置权限的bug repo

### ISSUE THREAD

**Issue by AuMgLi** [naco-siren/mogicians-manual#41]
三星s7 edge(sm-g9350), Android 7.0，长按设置铃声后弹出请求权限页面，允许后返回应用依然提示无权限

**Comment by naco-siren** [comment]
@AuMgLi 这个问题我在pixel和nexus 6p上没有遇到过，所以很遗憾这个bug我木法重现并fix。不过你可以考虑支援我一台boom 7……
