### ISSUE TITLE
投稿-失传的诗句

### ISSUE THREAD

**Issue by git-syl** [naco-siren/mogicians-manual#42]
长风破浪会有时，问我支持不支持。 一身去国六千里，我就明确告诉你。 渭川斜阳照墟落，哪个国家没去过。 百壶且试开怀抱，熟悉西方那一套。在天愿作比翼鸟，人生经验还太少。 长使英雄泪满襟，你们还是太年轻。 翠影红霞映朝日，有时甚至很幼稚。 千金散尽还复来，教你闷声发大财。莫笑农家腊酒混，弄出一个大新闻。 消息不通何计是，美国有个华莱士。 雪消门外千山绿，不知高到哪里去。 此夜有情谁不极，你们还要多学习。天若有情天亦老，你们倒有一个好。三山半落青天外，跑得比谁都要快。国家不幸诗家幸，从来没有要钦定。一日看遍长安花，将来宣传有偏差。三军不发无奈何，你们全都要负责。生乏黄金枉图画，今天得罪你一下。黄沙百战穿金甲，按照香港基本法。

**Comment by chenchangchao** [comment]
吼啊，滋磁

**Comment by naco-siren** [comment]
+1
