### ISSUE TITLE
该软件莫名钦（锁）定了我的铃声

### ISSUE THREAD

**Issue by JonathanHouten** [naco-siren/mogicians-manual#44]
CM13.0
在试用了软件的铃声设定功能以后，我发现只要一进设置-》声音就闪退 

现在我没法把铃声调回去了（清空设置的存储没用）

怎么办 现在以来电话我的生命就疯狂流逝。这可不好
顺便 能不能在唱中 增加导出音频的功能

**Comment by naco-siren** [comment]
@UzminTid 我也是一头雾水……我的pixel和nexus 6p是没问题的，我也不知道应该怎么fix

**Comment by JonathanHouten** [comment]
@naco-siren  我建议你修改“修改铃声的方式” 原本可能是使用setActualDefaultRingtoneUri，我建议使用"android.intent.action.RINGTONE_PICKER“来注册成铃声选择器，再用[这里](https://my.oschina.net/toxin/blog/108686)的方法来处理。我认为这样的姿势更加正确

**Comment by JonathanHouten** [comment]
我认为发生这种错误的原因是设置无法处理直接由setActualDefaultRingtoneUri设置的铃声，因为没有对应的铃声选择器，在设置中获取铃声名就会出现问题（瞎猜的，我也不是android程序员）

**Comment by JonathanHouten** [comment]
我刚刚用音乐播放器试过了，就可以，可能你得把文件copy到外存储区？？

**Comment by JonathanHouten** [comment]
public static void setRingtone(MediaWrapper song, Activity context){
        if (!Permissions.canWriteSettings(context)) {
            Permissions.checkWriteSettingsPermission(context, Permissions.PERMISSION_SYSTEM_RINGTONE);
            return;
        }
        File newringtone = AndroidUtil.UriToFile(song.getUri());
        if(newringtone == null || !newringtone.exists()) {
            Toast.makeText(context.getApplicationContext(),context.getString(R.string.ringtone_error), Toast.LENGTH_SHORT).show();
            return;
        }
        ContentValues values = new ContentValues();
        values.put(MediaStore.MediaColumns.DATA, newringtone.getAbsolutePath());
        values.put(MediaStore.MediaColumns.TITLE, song.getTitle());
        values.put(MediaStore.MediaColumns.MIME_TYPE, "audio/*");
        values.put(MediaStore.Audio.Media.ARTIST, song.getArtist());
        values.put(MediaStore.Audio.Media.IS_RINGTONE, true);
        values.put(MediaStore.Audio.Media.IS_NOTIFICATION, false);
        values.put(MediaStore.Audio.Media.IS_ALARM, false);
        values.put(MediaStore.Audio.Media.IS_MUSIC, false);
        Uri uri = MediaStore.Audio.Media.getContentUriForPath(newringtone.getAbsolutePath());
        Uri newUri;
        try {
            context.getContentResolver().delete(uri, MediaStore.MediaColumns.DATA + "=\"" + newringtone.getAbsolutePath() + "\"", null);
            newUri = context.getContentResolver().insert(uri, values);
            RingtoneManager.setActualDefaultRingtoneUri(
                    context.getApplicationContext(),
                    RingtoneManager.TYPE_RINGTONE,
                    newUri
            );
        } catch(Exception e) {
            Log.e(TAG, "error setting ringtone", e);
            Toast.makeText(context.getApplicationContext(),
                    context.getString(R.string.ringtone_error),
                    Toast.LENGTH_SHORT).show();
            return;
        }
       Toast.makeText(
                context.getApplicationContext(),
                context.getString(R.string.ringtone_set, song.getTitle()),
                Toast.LENGTH_SHORT)
                .show(); 
}

这个是vlc的处理方式，这个方式是正常的，但是我没法完全看懂，所以贴出来给您学习一个

**Comment by naco-siren** [comment]
这部分的功能我移除了（逃
你要是想做的话可以自己写！PR大欢迎！
