### ISSUE TITLE
华莱士节目访谈报道出现了偏差

### ISSUE THREAD

**Issue by Toothpick-overlord** [naco-siren/mogicians-manual#46]
华莱士节目访谈报道出现了偏差
参考视频：
                https://www.youtube.com/watch?v=0povNxZpUKE&t=215s
                https://www.youtube.com/watch?v=p4lVvVcraHM&t=1923s
可以再加上“看”吗

**Comment by naco-siren** [comment]
作为离线内容的话apk放不下，在线内容的话直接youtube就行了
