### ISSUE TITLE
希望可以加入长者档案馆（hachive）

### ISSUE THREAD

**Issue by Naive817** [naco-siren/mogicians-manual#47]
长者著作等身，有《新时期我国微电子工业的发展》等几个学报、翻译的多本书籍（如《机械制造厂电能的合理利用》），如果能把它们的pdf下载链接内置在软件中，就能让我们更好地提高自己的姿势水平，感受长者的人格魅力。
同时一些视频和红宝书的下载链接也是非常重要的，姜选研究会的压缩包是不错的选择。
祝开发顺利！

**Comment by naco-siren** [comment]
@Naive817 已在考虑之中，谢谢建议！

**Comment by vectorijk** [comment]
二院的档案工作做得不错

**Comment by naco-siren** [comment]
Resolved
