### ISSUE TITLE
Could you please withdraw the poem "Jiu Zhang Ji"?

### ISSUE THREAD

**Issue by xunkai55** [naco-siren/mogicians-manual#48]
Hi Naco-Siren,

Could you please withdraw the poem "Jiu Zhang Ji"? I'm the original author and still live in mainland. Time changes fast, and I want to keep my Shui Biao safe.

Thanks a lot!

**Comment by naco-siren** [comment]
@xunkai55 Is it okay if I only remove the author from the entry? Your poem had gone viral over mainland's internet long before my app was launched, and believe me, you would already have been investigated if they had ever meant to do that.

**Comment by xunkai55** [comment]
I think it could be better if you remove the poet at all.

I agree with you that they can already find me if they want. But as your App grows, they now have the chance to collect and "process" the articles and authors altogether for the first time.

The environment in mainland is changing rapidly. We can never be too careful. I'll soon migrate outside, so if possible, you could release that poem again. Thanks a lot!

**Comment by naco-siren** [comment]
@xunkai55 Alright. I have noted down and will remove it in next release.
Just a bit curious about how you heard about my app. Was it some other 2 ziban that introduced it to you?

**Comment by xunkai55** [comment]
Oh, that could be numerous... Besides 2 ziban friends, several friends on Net and elder alumni also forward it to me. At least 3-5 independent information sources.

(And that's why I start to feel nervous LOL. Your app really becomes famous)
