### ISSUE TITLE
江主席2000年新年贺词，对近一千年做了一些微小的总结，希望能够添加

### ISSUE THREAD

**Issue by jianghaha123** [naco-siren/mogicians-manual#49]
作者：死道友大本营
链接：https://www.zhihu.com/question/47236050/answer/149200907
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

2000年新年贺词（1999年12月31日） 
2000年到来的钟声，就要鸣响在我们这个星球的寥廓上空。人类文明的发展，即将进入一个新世纪，开启一个新千年。今夜，在世界的东方与西方、南方与北方，各国人民无分民族、无分信仰，都在为这一历史时刻的来临而欢欣鼓舞。 
　　首先，我向全国各族人民和海外侨胞，向世界各国的朋友们，祝贺新年快乐！并致以新世纪、新千年的最良好祝愿！ 
　　此时此刻，最能引起人们回顾既往，瞻望前程。只有正确地总结历史，才能更好地走向未来。 
　　一千年来，人类历史发生了沧桑巨变。人类文明从古代文明发展到了现代文明。人类社会经过封建社会进入了资本主义社会，并且在一些国家诞生了崭新的社会主义制度。人类的经济活动进到了工业经济时代，并正在转入高新技术产业迅猛发展的时期。人类创造了以往数千年无法比拟的巨大物质与精神财富。人类对世界的认识和改造，突破一个又一个必然王国而不断地向着自由王国飞跃。 
　　一千年来，人类进步取得的一切成就，都是在推陈出新的社会变革和科技进步中实现的。著名的文艺复兴运动，打破了欧洲中世纪的黑暗神学统治。和平与正义的伟大力量，战胜了各种横行世界的“霸主”及其发动的非正义战争。历时几个世纪的殖民主义体系，终于在本世纪风起云涌的民族解放运动中宣告终结。各国人民的卓越创造和广泛交流，汇成了推动历史前进的浩荡动力。要和平、求发展已成为当今世界的时代潮流。 
　早在这一千年前，中华民族就以发展了几千年的灿烂文明而著称于世界，并将这种领先地位一直保持到十五世纪。后来由于生产力发展的迟缓和社会政治的腐朽，中国逐渐落后了，以至于近代陷入了遭受列强欺凌的半殖民地半封建社会的悲惨境地。但是，中华民族没有屈服，而是前仆后继地进行艰苦卓绝的斗争。以毛泽东同志为代表的中国共产党，坚持把马克思主义基本原理同中国具体实际相结合，领导人民经过伟大的革命终于在本世纪中叶建立了新中国。中国从此进入了建设社会主义的新时代。现在，中国人民沿着邓小平同志开创的改革开放之路正在向现代化的彼岸阔步前进。 
　　进步终究要战胜落后，科学终究要战胜愚昧，正义终究要战胜邪恶，这是历史不断昭示人们的科学真理。世界和平与发展的崇高事业是不可阻挡的。面对新的世纪之交和千年之交，每个国家有远见的政治家都应从历史的高度思考：未来的世界应该是一个什么样的世界，应该为实现这样一个世界作出什么样的贡献。我们希望，在未来的世界，各个国家和各个民族能够始终和睦相处、友好合作、共同发展，能够建立起公正合理的国际政治经济新秩序，能够实现持久和平和普遍繁荣，各国人民都能够按照自己的意愿创造并享受美好的生活。世界正在走向多极化，这是历史发展的必然趋势，也是各国人民的共同愿望。中国人民愿与各国人民一道，为反对霸权主义和强权政治，推动多极化进程，创造世界美好的未来而共同奋斗！ 
　　我们坚信，在新世纪里，中国人民将坚定不移地沿着建设有中国特色社会主义道路继续前进，中国的社会主义制度将经过不断改革而更加巩固和完善，中国的发展将通过各个地区的共同进步达到普遍繁荣，中华民族将在完成祖国统一和建立富强民主文明的社会主义现代化国家的基础上实现伟大的复兴！

**Comment by naco-siren** [comment]
@jianghaha123 已添加，感谢投稿！
