### ISSUE TITLE
稿件建议-主席的SCI

### ISSUE THREAD

**Issue by lgp0509** [naco-siren/mogicians-manual#50]
好像论文都没有啊……当年science有一篇他写的science in China好像不是很长可以搞一下啊 一颗赛艇啊

**Comment by Naive817** [comment]
长者还有SCI？裤腰带太高了膜不起

**Comment by lgp0509** [comment]
Science  30 Jun 2000:Vol. 288, Issue 5475, pp. 2317  DOI: 10.1126/science.288.5475.2317
[http://science.sciencemag.org/content/288/5475/2317](url) 
![science in china science](https://user-images.githubusercontent.com/16364725/30531180-0ab0fc66-9c7f-11e7-83a5-6d3c06d763c4.png)

**Comment by naco-siren** [comment]
Done.
