### ISSUE TITLE
投稿一个段子

### ISSUE THREAD

**Issue by ghost** [naco-siren/mogicians-manual#53]
小哥的iPhone6s不小心掉到了湖里。这时，河神出现了，对他说：年轻人，请问你掉的是这部iPhone 5s呢，还是这部iPhone7呢？ 小哥：都不是，我掉的是iPhone 6s。 河神：你很诚实，这部iPhone 5s就给你吧！ 小哥：可是我掉的是6s，为什么给我5s呢？ 河神笑了笑，推了一下眼镜……
:grinning:

**Comment by catofmrlu** [comment]
你呀，too young😁
