### ISSUE TITLE
我觉得可以加个提供《他改变了中国》和《江选》下载的链接

### ISSUE THREAD

**Issue by wizard12138** [naco-siren/mogicians-manual#58]
老哥，能不能实现这个功能?我这有资源，PDF格式的。

**Comment by wizard12138** [comment]
[江泽民文选：第1卷.pdf](https://github.com/naco-siren/mogicians_manual_public_release/files/1374382/1.pdf)
[江泽民文选：第2卷.pdf](https://github.com/naco-siren/mogicians_manual_public_release/files/1374386/2.pdf)
[江泽民文选：第3卷.pdf](https://github.com/naco-siren/mogicians_manual_public_release/files/1374388/3.pdf)

**Comment by wizard12138** [comment]
https://share.weiyun.com/21b1b0942c4ccc1067e831ef59dd7f6c

**Comment by superxh** [comment]
> https://share.weiyun.com/21b1b0942c4ccc1067e831ef59dd7f6c

求更新一下资源，另求一份英文原版，如果有的话

**Comment by fleebeatles** [comment]
> https://share.weiyun.com/21b1b0942c4ccc1067e831ef59dd7f6c

链接失效了

**Comment by naco-siren** [comment]
Done.
