### ISSUE TITLE
【学】部分中“讲什么语”一条建议增补内容（附文献来源）

### ISSUE THREAD

**Issue by liukinbaku** [naco-siren/mogicians-manual#60]
在日语维基百科页面：
https://ja.m.wikipedia.org/wiki/%E6%B1%9F%E6%B2%A2%E6%B0%91
中的逸话部分有一条。
酔うと日本語で炭坑節を歌うことがある[1]。
喝醉了会用日语唱日本民歌《炭坑节》。
建议将以上内容进行增补
文献来源：
[1] ^ a b c 宮崎正弘『出身地でわかる中国人』（PHP研究所、2006年）、91ページ（91页）。

**Comment by naco-siren** [comment]
已Fix，靴靴！
