### ISSUE TITLE
投稿两个段子

### ISSUE THREAD

**Issue by glgjssyqyhfbqznavie** [naco-siren/mogicians-manual#68]
ta，是9人成员的老大，也是身高最矮的一个；ta，曾任某部部长，虽然时间很短，但是对这个部的成员很有感情；ta，曾经在卸任之前，钦点了某个名字里带有hua的人；ta,擅长歌唱，精通乐器，因为热爱音乐和某个性格泼辣，擅长高音的妹子走的很近；虽然ta的影响力逐渐衰弱，但仍有ta的忠贞教徒在时时刻刻膜拜ta，ta名字的第二个字是“泽”，

ta就是……矢泽妮可！

ta的姓有三点水。
ta出生在水边，喜欢音乐。
人们津津乐道于ta和一位擅长歌唱的少女的感情纠葛。
ta喜欢戴黑框眼镜。
ta就是。。。。渡边曜！

**Comment by naco-siren** [comment]
@glgjssyqyhfbqznavie 你要不要自己开个PR来编辑一下
