### ISSUE TITLE
作者小心！

### ISSUE THREAD

**Issue by THUzhangga** [naco-siren/mogicians-manual#7]
http://www.saraba1st.com/2b/forum.php?mod=viewthread&tid=1515609

**Comment by naco-siren** [comment]
@THUzhangga 哎呦谢谢提醒。小学弟是几字班的哦

**Comment by THUzhangga** [comment]
@naco-siren 师兄好，我是四字班，来自养老院...

**Comment by naco-siren** [comment]
@THUzhangga 啧啧啧，养老院上什么GitHub（逃

**Comment by THUzhangga** [comment]
@naco-siren 退git退git

**Comment by naco-siren** [comment]
@THUzhangga 你是认识嘉神么？我注意到你有一个Project Eular的repo……

**Comment by THUzhangga** [comment]
@naco-siren 抱歉不认识，project eular是很久之前试过的，但是太渣了玩不来就放弃了。。。

**Comment by dakkidaze** [comment]
七字班的瑟瑟发抖

**Comment by naco-siren** [comment]
@dakkidaze 那不是刚入学吗？？？

**Comment by dakkidaze** [comment]
@naco-siren
是啊，新生

**Comment by naco-siren** [comment]
@dakkidaze 年轻人不好好学习跑出来翻墙，啧啧啧

**Comment by dakkidaze** [comment]
@naco-siren
有v6全局免流量嘛。。
而且不登录就有ipv6.google.com和en.wikipedia.org用，没事就看iptv，想刷B站就开免流，基本够了

**Comment by naco-siren** [comment]
@dakkidaze 所以你就ShadowSocks了是吧

**Comment by dakkidaze** [comment]
@naco-siren
有shadowsocksr和anyconnect
不过大清的ipv6太烂了（也可能跟无线网有关系）
逛北邮pt站根本没法好好下载

**Comment by ghost** [comment]
6字班萌新瑟瑟发抖

**Comment by naco-siren** [comment]
@czy0409 六字班贵系？

**Comment by czy0409** [comment]
@naco-siren no... 化工学渣...
