### ISSUE TITLE
长者会的语言里应该增加广东话

### ISSUE THREAD

**Issue by ijayden-lung** [naco-siren/mogicians-manual#75]
长者在广东高州市开会的时候开场白”我讲嘅係普通话，希望你哋都听得懂，得唔得啊，吼唔好！“然后台下一片说好。
视频连链接: https://www.youtube.com/watch?v=ePM0SvcdSh4

长者会见侨胞的时候曾经用广东话作为开场白，和大家打成一片。
视频链接：https://www.youtube.com/watch?v=W0fst3fm1qk
广东话内容“”你哋吼啊，广东话我识听唔识讲“

期间还夹杂着英文，这个洋文好得很呐。

最后还唱了京剧。应该加入唱里面，唱里面太多鬼畜了，原版素材都没有，州长夫人的演唱也没有。

**Comment by naco-siren** [comment]
京剧的部分麻烦您开个PR
