### ISSUE TITLE
対於内容拡充的建議

### ISSUE THREAD

**Issue by Nagato-Kiangologiste** [naco-siren/mogicians-manual#79]
過去的一年中，膜法文化取得了不小的發展成績。
各界蛤絲在江学的各方面産生了大量的新成果，例如江学教科書及膜改大字報等膜圖、經考據新發現的長者語録、新發表的膜改歌曲（江学主義好，長者Bad Apple等）。
建議本應用対於收録的内容継續予以拡充，及時将這些新成果反映在這款聞名於各界蛤絲的應用中。

**Comment by naco-siren** [comment]
无资源言屌

**Comment by Nagato-Kiangologiste** [comment]
https://www.youtube.com/playlist?list=PLauVXX--jDm3UsaKWBogdQu7IToRrrF5y
https://t.co/7zwRzXyAFE
https://twitter.com/i/moments/1009011534712987648
https://zh.m.wikiquote.org/zh-hans/%E6%B1%9F%E6%B3%BD%E6%B0%91#1998年访问日本

参考資源如上

**Comment by naco-siren** [comment]
@NagatoVuncin 麻烦你开个PR来扩充吧
