### ISSUE TITLE
投稿:曹操自白

### ISSUE THREAD

**Issue by godmei** [naco-siren/mogicians-manual#81]
丞相：我的经历就是到了洛阳，到了公元196年年初的时候，我在想乱世估计也应该结束了， 我想我应该去当刺史。于是我就给安集将军董承，兴义将军杨奉，给他们写了一份报告。他们说欢迎你来，不过这个皇上蒙尘，你要兴复汉室还于旧都，我就迎接皇帝到了洛阳。这个举措经过好几百个士族一致通过。 
那么接回皇帝之后我就做了第二件事情，就是派裴茂去干掉了李傕。这两件事做了以后不久，我就把皇帝迁到了许昌。现在到许昌已经20多年了，所以去年把部队调回洛阳。就是呼应公元197年我迁都许昌的。特别是今年，我表孙权为骠骑将军，他还向我劝进，总共和我说了二十七句话。我也没有什么好留给后人的，听完以后我就叫贾诩呀，把这些话，这些话的吴语本，因为孙权一口南方口音啊，还有前面那些人的劝进书信，还有我写的《孟德新书》都抄下来送给曹丕。给他送过来，做个纪念。 
（此处有掌声） 
人那，就是不知道，自己都不可以预料。一个人的一生啊，除了依靠自我奋斗，还要考虑皇帝的赏识。我绝对不知道我作为一个宦官之后，怎么就给我加九锡了。所以皇帝就给我讲话，皇室都决定了，你来做魏王。我说另请高明吧，我实在也不是谦虚，我一个宦官之后怎么能加九锡了呢，但是，皇帝讲，大家已经研究决定了。后来我念了两句诗，叫 
“烈士暮年，壮心不已”然后我就做了魏王。 
在许昌我这二十几年也没什么别的，大概三件事。一个，是扫清了中原军阀割据，确立了汉室正统，第二个，把屯田制列入治国方针，第三就是废除三公。如果说还有一点成绩就是军队一律不得以踩踏农田，这个对农业的命运有很大关系。因为我从陈留开始起兵，等于我在部队做了三十年统帅。还有兴修水利也是很大的，但是这些都是次要的，我主要的就是三件事情， 很惭愧，只做了一点微小的工作，谢谢大家。

**Comment by naco-siren** [comment]
@godmei  麻烦您开个PR来添加吧
