### ISSUE TITLE
手机壳照片投稿

### ISSUE THREAD

**Issue by HouNextItem** [naco-siren/mogicians-manual#91]
我有一张手机壳照片 投稿
https://drive.google.com/file/d/1fbTauy12chKRpUzM4H1uoDyu7aqymDya/view?usp=drivesdk

**Comment by ARK3721** [comment]
我也想要一个啊啊啊啊啊（爆哭）

**Comment by naco-siren** [comment]
文件过期了（其实我也忘了我采纳还是没有采纳了）
