### ISSUE TITLE
高考表情包投稿

### ISSUE THREAD

**Issue by TonyShitDark** [naco-siren/mogicians-manual#94]
![SmartSelect_20190608-223541_Gallery](https://user-images.githubusercontent.com/32632071/59148688-a4dc0980-8a3e-11e9-8fc1-473a9d571f91.jpg)
![-4544df76ed585542](https://user-images.githubusercontent.com/32632071/59148691-adccdb00-8a3e-11e9-8f4c-34fbf179b7cc.jpg)
![e7cd5bb01656a03](https://user-images.githubusercontent.com/32632071/59148693-b58c7f80-8a3e-11e9-9c47-d4feadca0440.jpg)

**Comment by TonyShitDark** [comment]
能稍微修一下图就更好了

**Comment by EsawaAzusa** [comment]
谁还有那个，上海卷作文阅卷现场，一堆蛤从屏幕里跳出来的表情包？

**Comment by naco-siren** [comment]
这几个表情包画质实在太差，先不考虑了
