### ISSUE TITLE
请添加此视频中的评论和新蛤社新作长者点灯

### ISSUE THREAD

**Issue by EsawaAzusa** [naco-siren/mogicians-manual#97]
av9116665
有一句古诗词我们倒背如流。
有几个英文单词我们过目不忘。
也许我们互不相识，但我们总能交流到一个话题上。
我们的接龙是最默契的。
几个字，几张图，甚至几个符号，都能让我们会心一笑。
黑到深处自然粉，他为中国的贡献我们也知道。
多年后，也许他真的不在了，我们才会惋惜，曾经的时光。
如今评论区关闭，这可能是最后一个池塘。
我们不是邪教，我们是，真正的粉丝。
今年今日评论区，赛艇吼蛙相映红。虫合不知何处去，长0者依旧笑春风。——只属于我的小尾巴，一位真正的粉丝

我们可以看一下中国第一位网络红人，也是中国最具人气的网络红人，他走红网络十几年，他创造的网络流行词和他一起走红网络十几年，不仅没有过气，反而近几年大有卷土重来之势。
他从不在网络社区抛头露面，但每个网站都有他的传说。
他从不和粉丝互动，但粉丝爱他就像爱生命。
他没有利用自己的名声去搞自媒体，但大家却自发研究他的重要思想。
他不借助自己的社会关系办公司开淘宝搞代购，但粉丝愿意默默为他捐献。
他著作等身，但从未在书中灌一滴鸡汤。
他留给网民的并不是一场喧嚣的狂欢，而是取之不尽的经验。
希望他能够成为全体网络红人的楷膜。

“给你猜一个人。他的父亲是**烈士，由伯父抚养成人……”
“沙瑞金。”
“他有个青梅竹马的妻子，家中还有两个孩子……”
“侯亮平。”
“但他还是和一位唱曲儿的年龄悬殊的姑娘有不清不白的关系……”
“祁同伟。”
“他曾经一心想做教授，但组织还是钦点他当了领导。”
“高育良。”
“他在当****的时候，曾力挽狂澜，解决了一场颇有影响的群体事件，进入了上级的视野……”
“李达康。”
“虽对经济发展贡献颇大，可同时他也是工**批下岗的幕后主导者……”
“丁义珍。”
“他还间接导致在公共场合的人烧事件，海内外一片哗然……”
“蔡成功。”
“也有人对他颇有微词，认为他阻碍了大批老人从事商业活动……”
“孙连城。”
“如今，他仍然退而不休，拥有重大的政治影响力……”
“陈岩石。”
“甚至有传闻说他的儿子利用他的影响力牟利……”
“赵立春。”
“他也因为在香港与媒体工作者的接触引发更大的关注……”
“赵瑞龙。”
“甚至连他口中吟诵的几句诗歌，也引发了众多的议论……”
“郑西坡。”
“可今天，他仍然无处不在，无时无刻不在暗中观察一切。他是永远受人尊敬的，生命力更是无穷的，可官方却总是想方设法回避他，只因为不敢正视他的名字在人们心中的无限崇高！”
“人民，这就是人民啊！”

旅行青蛙身上纹，掌声送给淋到人。
身经百战见的多，哪个国家没去过？
谈笑风生华莱士，努力学习长知识。
不学无术没知识，问的问题太幼稚。

长者点灯：
https://www.youtube.com/watch?v=4PsvTcYGHmI

**Comment by naco-siren** [comment]
+1

**Comment by shjknfhej** [comment]
我是一个年轻人，图样图森破，真心请教，经常在网上看到评论区接龙诗句，抽象符号什么的，后来了解到是他，但还是搞不清楚网友对他的态度是黑还是粉。还有好多符号和词都不知道是什么意思。比如+1s，听说好像是网友对他的祝福，给他增加寿命？还有前一段时间网上穿出应该女王伊丽莎白的新闻时，又看到关于他的热议，看评论区好像是他们直接有个长寿比赛似的，我搞不清楚。还有穿红衣那个，是指以前红衣男孩案是真的用来给他续命的吗？还有网友看到有人提及他有关的词，经常会说不要命了，子弹滞销了，这是为什么？是真的以前有人因为说他的坏话或者是开他的玩笑被枪决了吗？还有炸弹人💣那个和子弹是同一个道理吗？希望能给我这个图样图森破指点迷津，谢谢
