### ISSUE TITLE
有没有可能出一个iOS版本呢

### ISSUE THREAD

**Issue by TonyShitDark** [naco-siren/mogicians-manual#99]
如题

**Comment by sanlushibawan** [comment]
作者已经出了flutter版本了，Android iOS 都可以用哦

**Comment by TonyShitDark** [comment]
> 作者已经出了flutter版本了，Android iOS 都可以用哦

在什么地方？可以发一下链接吗？

**Comment by sanlushibawan** [comment]
@wsdd977  naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。

**Comment by TonyShitDark** [comment]
> @wsdd977 naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。

项目链接发一下谢谢

**Comment by sanlushibawan** [comment]
> > @wsdd977 naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。
> 
> 项目链接发一下谢谢

[其实就是你提问题的这个项目](https://github.com/naco-siren/mogicians-manual)

**Comment by TonyShitDark** [comment]
> > > @wsdd977 naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。
> > 
> > 
> > 项目链接发一下谢谢
> 
> [其实就是你提问题的这个项目](https://github.com/naco-siren/mogicians-manual)

这是安卓的源码啊.....

**Comment by sanlushibawan** [comment]
> > > > @wsdd977 naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。
> > > 
> > > 
> > > 项目链接发一下谢谢
> > 
> > 
> > [其实就是你提问题的这个项目](https://github.com/naco-siren/mogicians-manual)
> 
> 这是安卓的源码啊.....

[说明文档在app目录下](https://github.com/naco-siren/mogicians-manual/tree/master/app)

**Comment by TonyShitDark** [comment]
> > > > > @wsdd977 naive，这个需要自己克隆项目编译啦，毕竟上架App Store要审核的。
> > > > 
> > > > 
> > > > 项目链接发一下谢谢
> > > 
> > > 
> > > [其实就是你提问题的这个项目](https://github.com/naco-siren/mogicians-manual)
> > 
> > 
> > 这是安卓的源码啊.....
> 
> [说明文档在app目录下](https://github.com/naco-siren/mogicians-manual/tree/master/app)

看到了是我naive了
